### ISSUE TITLE
Action items checklist

### ISSUE THREAD

**Issue by atharva620** [personalrobotics/geodude_ros2#9]
### Priority:
- [ ] [Atharva] Work on #7 
- [ ] [Bernie]Send a support request to Vention for station stabilization
- [ ] [Bernie]Install cable management kits
- [ ] [Bernie]Install Kinect cameras
- [ ] [Bernie]Hand eye calibration
- [ ] [Bernie]Tactile sensor
- [x] [Bernie/Atharva] Update system (/etc) barret config w/ zerocal info. Make sure simplemove works
- [x] Also add zerocal.conf and calibration.conf to geodude_hardware/config/ and make a PR
- [ ] Update wiki: copy config files from geodude_hardware to etc
- [ ] [Note]: in our code (hw interface) make sure config file is configurable [modify CMakeLists.txt to install config directory into the share directory, and then pass in a file to HW interface relative to that share directory]
- [ ] [Bernie/Atharva]Rviz support for geodude
- [ ] [Bernie/Atharva] For auto-tensioning, order a small table as shown at https://support.barrett.com/wiki/WAM/HardwareSetup from Barrett.
- [ ] [Bernie] Add IP address mappings to PRL Wiki
- [ ] [Bernie/Atharva] Update wiki on making the Ubuntu 22 control machine (e.g. libbarrett into /opt, etc.)

### Second Arm Stuff:
- [ ] Create your own reset_can.sh that does Can0 and Can1 (port 0, port 1), install in scripts folder in geodude_hardware
- [ ] Do gravcomp + zerocal for right arm, save it to the geodude_hardware/config
- [ ] Modify geodude_hardware.xacro to include 2 copies of barrett object, each one with a different configuration file (hardware interface accept a configuration file)

- [ ] [Helen] Make 2 PRs (geodude_ros2 and geodude_description)
- [ ] [Ethan] Review + Merge PRs
- [ ] [Atharva] Make geodude_description PR, back-merge main after Ethan merges Helen’s PRs
- [ ] [Helen] isaacsim hw interface in geodude_hardware
- [ ] [Helen] Lower Pri: Create a docker config (ROS2 [iron ideally] + Isaac + libbarrett[?]) and add to geodude_ros2

### Lower Priority:
- [ ] Test display pendant from WAMs
- [ ] Merge E-Stops Vention + WAMs
- [ ] Interface for Demo Collection

**Comment by atharva620** [comment]
Transferred to Geodude Trello board
